### ISSUE TITLE
Problem with Finding Some Shows Correct Title

### ISSUE THREAD

**Issue by Zarthes** [jamerst/AutoTag#1] opened 2020-03-20 12:38 UTC
Dear Sir:

first let me thank you for you awesome work, I've lot's of .mkv files and were looking for a program that could find and add online metadata to my .mkv files. but I couldn't find a program to do that WITHOUT converting existing .mkv file. I'm not sure how but your awesome program can change and add online metadata to .mkv files WITHOUT converting them. as I said I tried lots of programs but none of them did the job as yours did. so you are LIFESAVER.

Now I would like to address some minor issues & some suggestion. sometimes application tags wrong tv show even the name of downloaded .mkv file is correct ( like: penny.dreadful.s01.e01) but it adds another shows tag to metadata. if you could able to add an option to edit match  (like PLEX media server rematch option).in from Plex media server when you rematch it shows you the shows/movies with exact name to choose the right one(like : The office, The office U.S)

**Comment by jamerst** [comment] 2020-03-23 16:24
I'm aware of this issue, I've actually encountered it myself.

It's caused by TVDb returning wrong results, I plan to improve it and add a manual tagging mode, but I probably won't have time for a couple of months yet.

It will be fixed _eventually_.

**Comment by zyw80** [comment] 2020-05-29 18:42
While we wait for a fix, there is any way to get around the problem?

**Comment by jamerst** [comment] 2020-05-29 21:13
Unfortunately not, without just modifying the code to select the correct result on a case-by-case basis (which is what I've been doing).

I should have more time after next week, so it should hopefully be fixed fairly soon.

**Closed** 2020-07-02 15:35 UTC

**Comment by jamerst** [comment] 2020-07-02 15:40
Apologies for the delay, this should now be fixed or at least improved in v2.1.0.

**Comment by jamerst** [comment] 2020-07-17 15:43
v3.0.0 now has a full manual tagging mode, so this should allow any mismatches to be easily overridden manually.
